### ISSUE TITLE
I wonder how to compute the PSR. 

### ISSUE THREAD

**Issue by mangoocmt** [amoudgl/mosse-tracker#1]

**Comment by amoudgl** [comment]
To calculate PSR, 

- Find the mean (say `mean`) and standard deviation (`std`) of the output response (which is basically `IDFT(DFT(filter) * DFT(img))`). 
- Calculate the peak value of the output response (calculated as `maxval = max(gi(:));` in `src/mosse.m`)).  

PSR is given by: 

`PSR = (maxval - mean) / (std + eps)` 

where `eps` is the same variable used in `src/preprocess.m`.
