### ISSUE TITLE
Have you implemented the epsilon (the regularization paramter)?

### ISSUE THREAD

**Issue by mangoocmt** [amoudgl/mosse-tracker#2]

**Comment by amoudgl** [comment]
No, regularization parameter, as stated in the paper for producing more stable ASEF filters has not been implemented. However, an epsilon parameter `eps` is used to preprocess image by taking reference from the OpenCV implementation: 

https://github.com/opencv/opencv/blob/master/samples/python/mosse.py

**Comment by mangoocmt** [comment]
Thank you very much.
